import { View, Text, StyleSheet, Pressable } from "react-native";
import { useEffect, useState } from "react";
import * as WebBrowser from "expo-web-browser";
import * as Google from "expo-auth-session/providers/google";
import * as AuthSession from "expo-auth-session";
import { useRouter } from "expo-router";

WebBrowser.maybeCompleteAuthSession();

export default function SignUp() {
  const router = useRouter();
  const [signingIn, setSigningIn] = useState(false);

  // ✅ Expo Go should use the proxy redirect generated by AuthSession
  //const redirectUri = AuthSession.makeRedirectUri({ useProxy: true });
  const redirectUri = AuthSession.makeRedirectUri({ useProxy: true });

  console.log("redirectUri computed:", redirectUri);
  const [request, response, promptAsync] = Google.useAuthRequest({
    // ✅ FIXED: must be .com
    webClientId:
      "820527515652-glssibulbtjnq7vqur6hfg517k6lqbf1.apps.googleusercontent.com",

    // Keep this if your library complains on iOS
    iosClientId:
      "820527515652-3ap73pd55flp82elvtsbpct1rjk23n3o.apps.googleusercontent.com",

    redirectUri,
    scopes: ["openid", "profile", "email"],
  });

  useEffect(() => {
    console.log("redirectUri:", redirectUri);
    console.log("request.redirectUri:", request?.redirectUri);
    console.log("request.url:", request?.url);
    console.log("response:", response);
  }, [redirectUri, request, response]);

  useEffect(() => {
    if (response?.type === "success") {
      console.log("AUTH:", response.authentication);
      router.replace("/(tabs)");
    } else if (response?.type === "error") {
      console.log("ERROR:", response.error);
    }
  }, [response, router]);

  const handleGoogleSignIn = async () => {
    if (!request || signingIn) return;
    setSigningIn(true);
    try {
      await promptAsync({ useProxy: true });
    } finally {
      setSigningIn(false);
    }
  };

  return (
    <View style={styles.container}>
      <Pressable
        style={[styles.button, (!request || signingIn) && styles.buttonDisabled]}
        onPress={handleGoogleSignIn}
        disabled={!request || signingIn}
      >
        <Text style={styles.buttonText}>
          {signingIn ? "Signing in..." : "Sign in with Google"}
        </Text>
      </Pressable>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, justifyContent: "center", padding: 24, backgroundColor: "white" },
  button: { backgroundColor: "#C7F36B", padding: 15, borderRadius: 14, alignItems: "center" },
  buttonDisabled: { opacity: 0.6 },
  buttonText: { fontWeight: "600", fontSize: 16, color: "#333" },
});